name: Deployment
on:
  push:
    branches:
      - main

  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      sha:
        description: 'sha to deploy'
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read
  packages: read

env:
  SHA: ${{ inputs.sha || github.sha }}
  APP_ASSET_PATH: /b/a/ecom-website/${{ inputs.sha || github.sha }}
  ECR_REPOSITORY_NAME: ecom-website

jobs:
  # echo the sha to the console
  echo_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Echo SHA
        run: 'echo "SHA: ${{ env.SHA }}"'
